# Generated by Django 5.2.3 on 2025-07-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningservice',
            name='category',
            field=models.CharField(choices=[('rumah', 'Rumah'), ('kantor', 'Kantor')], default='rumah', max_length=20),
        ),
    ]
